# Generated by Django 5.2.4 on 2025-07-12 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('weight', models.IntegerField(help_text='weight in kg')),
                ('activity_level', models.CharField(max_length=50)),
                ('goal', models.CharField(max_length=100)),
                ('h1', models.IntegerField(help_text='height in meter for bmi')),
                ('h2', models.IntegerField(help_text='height in cm for calorie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
