# Generated by Django 5.2.4 on 2025-07-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='goal',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='h1',
            field=models.FloatField(help_text='height in meter for bmi'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='h2',
            field=models.FloatField(help_text='height in cm for calorie'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='weight',
            field=models.FloatField(help_text='weight in kg'),
        ),
    ]
