# Generated by Django 5.2.4 on 2025-07-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0002_remove_userinfo_goal_alter_userinfo_h1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='protein_req',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
