# Generated by Django 5.2 on 2025-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0003_userinfo_protein_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nutrition',
            field=models.JSONField(default={}),
        ),
    ]
