# Generated by Django 5.2 on 2025-08-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0004_userinfo_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='protein_eaten',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
