# Generated by Django 5.2 on 2025-08-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0005_userinfo_protein_eaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='protein_eaten',
            field=models.FloatField(default=0),
        ),
    ]
