# Generated by Django 5.2 on 2025-08-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0007_alter_userinfo_protein_eaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='protein_req',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
