# Generated by Django 5.2 on 2025-08-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0010_alter_userinfo_protein_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='protein_req',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
