# Generated by Django 5.2 on 2025-08-30 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0011_alter_userinfo_protein_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='date_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
