# Generated by Django 5.2 on 2025-09-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0012_userinfo_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='protein_eaten',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='protein_req',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
