# Generated by Django 5.2 on 2025-09-02 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0013_alter_userinfo_protein_eaten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='protein_eaten',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
