# Generated by Django 5.2 on 2025-09-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0014_alter_userinfo_protein_eaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='protein_eaten',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
