# Generated by Django 5.2 on 2025-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0015_alter_userinfo_protein_eaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='calorie_eaten',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='calorie_req',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
