# Generated by Django 5.2 on 2025-09-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0016_userinfo_calorie_eaten_userinfo_calorie_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='goal',
            field=models.CharField(default='', max_length=50),
        ),
    ]
