# Generated by Django 5.2 on 2025-09-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0017_userinfo_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='calorie_req',
            field=models.PositiveIntegerField(),
        ),
    ]
