# Generated by Django 5.2 on 2025-09-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0018_alter_userinfo_calorie_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='calorie_req',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
