# Generated by Django 5.2 on 2025-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0019_alter_userinfo_calorie_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('calorie', models.FloatField()),
                ('protein', models.FloatField()),
            ],
        ),
    ]
