# Generated by Django 5.2 on 2025-12-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0020_nutritionaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionaldata',
            name='id',
        ),
        migrations.AlterField(
            model_name='nutritionaldata',
            name='food_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
