# Generated by Django 5.2 on 2026-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0021_remove_nutritionaldata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bmi_req',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nutrition',
            field=models.JSONField(default=dict),
        ),
    ]
