# Generated by Django 5.2 on 2026-02-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0022_userinfo_bmi_req_alter_userinfo_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionaldata',
            name='serving_size',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
