# Generated by Django 5.2 on 2026-02-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0023_nutritionaldata_serving_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionaldata',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
