# Generated by Django 5.2 on 2026-02-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitzy_app', '0024_nutritionaldata_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionaldata',
            name='quantity',
        ),
    ]
